[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Enable Netlify Image CDN and Sharp
  NEXT_SHARP_PATH = "/node_modules/sharp"
  ENABLE_IMAGEMAGICK = "true"

# Enable Netlify Image CDN and Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Image optimization with Netlify Image CDN
[[redirects]]
  from = "/_netlify/images/*"
  to = "https://api.netlify.com/image/v1/:splat"
  status = 200
  force = true

# Next.js specific routes
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Scheduled Functions
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

# Configure the scheduled function
[functions."fetch-news-cron"]
  schedule = "*/15 * * * *"  # Her 15 dakikada bir

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings for images and assets
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache settings for images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

# Handle image optimization requests
[[redirects]]
  from = "/_netlify/images"
  to = "/_next/image"
  status = 200
  force = true
  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

# Serve static images directly
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"