[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Ensure proper routing for Next.js app directory
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle SPA routing for client-side navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes should not be redirected
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Static assets should not be redirected
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Netlify Image CDN configuration for remote images
[images]
  remote_images = [
    "https://image.dunya.com/.*",
    "https://cdn.example.com/.*",
    "https://images.unsplash.com/.*",
    "https://*.dunya.com/.*"
  ]
  max_size = "10mb"
  min_size = "1kb"